services:
  crosstalk:
    container_name: crosstalk
    image: ghcr.io/buildwithparallel/crosstalk:latest
    pull_policy: always
    restart: unless-stopped
    # Make the crosstalk web interface accessible from the host on port 8000
    ports:
      - 0.0.0.0:8000:8000
    volumes:
      - crosstalk-config:/config
    # Uncomment if you have a USB device connected, such as an RNode
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0

volumes:
    crosstalk-config:
